### ISSUE TITLE
Singularity Hub

### ISSUE THREAD

**Issue by vsoch** [bitb3ast/UITS#1]
hey @bitb3ast ! Do you mean to be building on Singularity Hub? The reason the builds are failing is because there needs to be a [Singularity](Singularity) file in the base of the repo (and it looks like you have a folder). see here --> https://singularity-hub.org/collections/96/ Let me know if you need help!

**Comment by bitb3ast** [comment]
@vsoch Thanks for the update, I shall change it to singularity files.

**Comment by vsoch** [comment]
great! Thanks for looking into this. Let me know if you have any questions, etc.
